# Generated by Django 3.0.8 on 2020-08-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200815_1057'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
